# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.8.5

clone:
  depth: full

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip install --upgrade pip
          - pip install -r requirements.txt
          - git push --force https://heroku:ce95c032-6fc4-4d13-bc26-1461ad00b64c@git.heroku.com/sirle-foods-data.git HEAD
