# -*- coding: utf-8 -*-

CATEGORIES = {
    "Jäätised": 39,
    "Kalatooted": 15,
    "Kastmed, ketšupid, majoneesid, sinepid": 18,
    "Keedised, kompotid, mesi": 19,
    "Kondiitrikaubad, toidukontsentraadid": 20,
    "Konserv valmistoidud, konservid": 21,
    "Kuivained, pastad, müslid": 13,
    "Kulinaariatooted": 24,
    "Külmutatud köögi-ja puuviljad": 11,
    "Lihatooted": 16,
    "Maitseained": 25,
    "Maiustused": 12,
    "Pagaritooted": 37,
    "Piimatooted, munad": 14,
    "Puu-ja juurviljad": 38,
    "Tervisekaubad": 34,
    "Toidurasvad": 22,
    "Joogid": 29,
    "Kohv, tee, kakao": 17,
    "Apteegikaubad": 2,
    "Elektrikaubad": 33,
    "Kodukeemia": 4,
    "Kontori- ja koolitarbed": 5,
    "Lemmikloomakaubad": 30,
    "Majapidamistarbed": 6,
    "Muud": 31,
    "Nõud ja pakkematerjalid": 36,
    "Paberikaubad": 7,
    "Parfümeeria": 8,
    "Kange alkohol": 26,
    "Lahja alkohol": 27,
    "Tubakas": 10,
    "Õlled": 28
}
