name: Run Scraper

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Create .env file
      run: echo "MONGO_DB_URI=${{ secrets.MONGO_DB_URI }}" > .env
    
    - name: Run scraper
      run: python scraper.py --no-details
